// ==========================================================================
// 80's style synthesizer ('synth' command)
//
// The synth chroma turns the PRISM into a square wave tone generator with
// a 1MHz PWM amplitude DAC on uo_out[7] (the audio PMOD):
//
//   comm     = PWM duty D.  31 = silence, 31 +/- a = volume a/32
//   compare  = 62 (carrier period = 64 clocks = 1MHz)
//   preload  = note half period in clocks (~32e6 / freq)
//
// The FSM raises the interrupt at every phase swap (twice per note
// period).  The CPU can ignore it (steady square wave) or use it to
// alternate two preload values (variable pulse width / PWM sweep) or to
// load LFSR random half periods (noise / percussion).  Volume envelopes,
// vibrato and pulse width sweeps are all just register byte writes.
// ==========================================================================

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <gpio.h>
#include <csr.h>
#include <uart.h>
#include <prism.h>
#include "prism_tui.h"
#include "synth.h"

// Note-progression sink (see synth.h): NULL = plain printf to console.
// The TUI points this at its Notes tab while it is on screen.
int (*synth_note_out)(const char *fmt, ...);

// Chroma bitstream generated by the PRISM Yosys backend (chroma_synth.v,
// tinyqv.cfg).  Square wave tone generator with a 1MHz PWM amplitude DAC
// on uo_out[7]: comm = duty (volume), compare = 62 (carrier period 64),
// preload = note half period in clocks.  Interrupt on each phase swap.
const uint32_t chroma_synth[PRISM_CHROMA_WORDS*2] = {
    0x000003d4, 0x00008000,
    0x000002ba, 0x00800015,
    0x000002a4, 0x02c0c016,
    0x00000296, 0x0280a01e,
    0x000003d6, 0x00000000,
    0x000002b8, 0x00c08015,
    0x000002a4, 0x02804016,
    0x00000294, 0x02c0201e,
};
// CHROMA_SYNTH_CTRL is in prism_tui.h

// Note half periods for octave 1 (32e6/freq - 32, centering the 64-clock
// carrier grid rounding).  Octave n is a right shift by n-1.
// Scale a 64MHz-referenced half period to the real clock (the -32
// carrier-grid centering is in fixed 64-clock carriers, so it is
// removed, scaled, and re-applied)
static uint32_t note_scaled(uint32_t p)
{
    if (clock_hz == 64000000u)
        return p;
    return (uint32_t)(((uint64_t)(p + 32) * clock_hz) / 64000000u) - 32;
}

static const uint32_t synth_note_p[12] = {
    978466, // C1  32.70 Hz
    923547, // C#1 34.65 Hz
    871710, // D1  36.71 Hz
    822783, // D#1 38.89 Hz
    776602, // E1  41.20 Hz
    733013, // F1  43.65 Hz
    691870, // F#1 46.25 Hz
    653037, // G1  49.00 Hz
    616383, // G#1 51.91 Hz
    581786, // A1  55.00 Hz
    549131, // A#1 58.27 Hz
    518309, // B1  61.74 Hz
};
static const char synth_note_name[12][3] = {
    "C-", "C#", "D-", "D#", "E-", "F-", "F#", "G-", "G#", "A-", "A#", "B-"
};

// FastTracker style keyboard: bottom row = base octave, top row = base+1
static const char synth_keys_lo[] = "zsxdcvgbhnjm";
static const char synth_keys_hi[] = "q2w3er5t6y7u";



const synth_preset_t synth_presets[] = {
    { "lead",  WAVE_SQUARE, 0,   0,  0,   0,   0,  8, 3200, 16 },
    { "brass", WAVE_SQUARE, 0,   6, 12, 180,  64,  8, 3400, 12 },
    { "pulse", WAVE_PULSE,  64,  0,  0,   0,   0,  8, 3200, 16 },
    { "thin",  WAVE_PULSE,  32,  0,  0,   0,   0,  8, 3200, 16 },
    { "pwm",   WAVE_SWEEP,  128, 0,  0,   0,  32,  4, 3300,  8 },
    { "bell",  WAVE_SQUARE, 0,   0,  0,   0,   0,  3,    0, 24 },
    { "drum",  WAVE_NOISE,  0,   0,  0,   0,   0, 24,    0, 48 },
    { "shaku", WAVE_FLUTE,  0,   5, 14, 400,  48,  6, 3100, 10 },
    { "laser", WAVE_LASER,  6,   0,  0,   0,   0, 20,    0, 40 },
    { "gun",   WAVE_GUN,    4,   0,  0,   0,   0, 40,    0, 60 },
    { "boom",  WAVE_BOOM,   6,   0,  0,   0,   0,  5,    0,  8 },
};
#define NUM_PRESETS ((int)(sizeof(synth_presets) / sizeof(synth_presets[0])))


static const int8_t synth_vib_sin[16] = {
    0, 3, 6, 7, 8, 7, 6, 3, 0, -3, -6, -7, -8, -7, -6, -3
};

// Synth engine state (struct defined in synth.h)
synth_state_t syn;


static const uint8_t synth_duo_iv[]        = { 0, 12, 7, 4 };
static const char *const synth_duo_name[]  = { "off", "octave", "fifth", "third" };
#define NUM_DUO ((int)(sizeof(synth_duo_iv) / sizeof(synth_duo_iv[0])))

// Recompute the preload value(s) from base_p, vibrato and pulse width,
// and stage them for the FSM
static void synth_apply_pitch(void)
{
    uint32_t p = syn.base_p;

    if (syn.pre->vib_depth && syn.gate_ms > syn.pre->vib_delay) {
        int32_t d = (int32_t)(p >> 10) * synth_vib_sin[syn.vib_phase]
                    * syn.pre->vib_depth;
        p += d >> 3;
    }

    if (syn.pre->wave == WAVE_PULSE || syn.pre->wave == WAVE_SWEEP) {
        uint8_t pw = syn.pre->wave == WAVE_SWEEP ? syn.pw_cur : syn.pre->pw;
        uint32_t p2 = p << 1;
        uint32_t ta = (p2 >> 8) * pw;

        if (ta < SYNTH_MIN_HALF)
            ta = SYNTH_MIN_HALF;
        if (ta > p2 - SYNTH_MIN_HALF)
            ta = p2 - SYNTH_MIN_HALF;
        syn.t_a = ta;
        syn.t_b = p2 - ta;
    } else {
        syn.t_a = syn.t_b = p;
    }

    // Stage for the next phase swap; the alternation between t_a and t_b
    // is kept up by the interrupt polling in the main loop.  The flute
    // voice keeps the FSM oscillator running at the plain note period,
    // and the laser dive rewrites it every ms.
    if (syn.pre->wave == WAVE_SQUARE || syn.pre->wave == WAVE_FLUTE ||
            syn.pre->wave == WAVE_LASER)
        prism_write32(PRISM_REG_PRELOAD, p);
}

// Change pitch without retriggering the envelope (arpeggios, slides)
static void synth_set_pitch(int semi, int oct)
{
    if (oct < 1)  oct = 1;
    if (oct > 8)  oct = 8;
    syn.base_p = note_scaled(synth_note_p[semi] >> (oct - 1));
    syn.pitch_target = syn.base_p;
    synth_apply_pitch();
}

// Set the arpeggiator cycle: base plus up to two intervals packed as
// nibbles (lo first, 0 = unused).  ms = 0 selects the default chip rate.
void synth_set_arp(uint8_t base, uint8_t intervals, uint8_t ms)
{
    syn.arp_note[0] = base;
    syn.arp_n = 1;
    if (intervals & 0xF)
        syn.arp_note[syn.arp_n++] = base + (intervals & 0xF);
    if (intervals >> 4)
        syn.arp_note[syn.arp_n++] = base + (intervals >> 4);
    syn.arp_ms = ms ? ms : SYNTH_ARP_MS;
    syn.arp_idx = 0;
    syn.arp_tmr = 0;
}

void synth_note_on(int semi, int oct)
{
    syn.env_state = ENV_ATTACK;
    syn.gate_ms = 0;
    syn.vib_phase = 0;
    syn.vib_div = 0;
    // Live keyboard duo mode; the demo sequencer overrides this with the
    // event's own arp setting right after
    synth_set_arp((uint8_t)(oct * 12 + semi), synth_duo_iv[syn.duo],
                  SYNTH_DUO_MS);
    synth_set_pitch(semi, oct);
    // Flute notes scoop up into pitch: start ~3% flat and glide in
    if (syn.pre->wave == WAVE_FLUTE) {
        syn.base_p += syn.base_p >> 5;
        synth_apply_pitch();
    }
    // Make sure the very next swap picks up the new pitch
    prism_write32(PRISM_REG_PRELOAD, syn.t_a);
    note_out("%s%d ", synth_note_name[semi], oct);
}

void synth_note_off(void)
{
    if (syn.env_state != ENV_IDLE && syn.env_state != ENV_RELEASE)
        syn.env_state = ENV_RELEASE;
}

// Flute voice.  A shakuhachi style tone is mostly a sine, which a square
// wave synth can't play - but the FSM flips output polarity at every
// phase swap anyway, so if the amplitude traces a half-sine lobe between
// swaps (resynced by the swap interrupt), the filtered output IS a sine.
// Breath comes from LFSR noise mixed into the amplitude, strongest during
// the attack; the pitch scoop and the deep delayed vibrato do the rest.
static const uint8_t synth_halfsine[16] = {
    25, 74, 120, 162, 198, 226, 245, 254,
    254, 245, 226, 198, 162, 120, 74, 25
};

static void synth_flute_service(void)
{
    uint32_t now = read_time();

    // Phase swap: the FSM just started the opposite lobe - restart ours
    if (prism_read32(PRISM_REG_CTRL) & PRISM_CTRL_INTERRUPT) {
        prism_write8(PRISM_REG_HOST_TOGGLE, SYNTH_M);
        syn.flute_step = 0;
        syn.flute_next = now;
    }

    if ((int32_t)(now - syn.flute_next) < 0)
        return;
    // 16 amplitude samples per half period: base_p/64MHz/16 = base_p>>10 us
    syn.flute_next = now + (syn.base_p >> 10);

    if (syn.env_state == ENV_IDLE) {
        prism_comm_write(SYNTH_CENTER);
        return;
    }

    uint16_t amp16 = (uint16_t)(syn.level >> 7) * syn.vel16;        // 0..480
    int a = ((int)synth_halfsine[syn.flute_step] * amp16) >> 12;    // 0..29
    if (syn.flute_step < 15)
        ++syn.flute_step;       // hold near zero until the swap resyncs

    // Breath: a whisper of noise always, a strong burst while the note
    // starts (the shakuhachi attack "chiff")
    int breath = 1 + (syn.gate_ms < 128 ? (int)((128 - syn.gate_ms) >> 4) : 0);
    syn.lfsr = (syn.lfsr >> 1) ^ (-(syn.lfsr & 1) & 0xB400);
    a += (((int)(syn.lfsr & 15) - 8) * breath) >> 3;

    if (a < 0)  a = 0;
    if (a > 30) a = 30;
    prism_comm_write((uint8_t)(SYNTH_CENTER + a));
}

// Phase swap interrupt service: keep the pulse width alternation (or the
// noise generator) fed.  The host-toggle write clears the interrupt and
// rewrites the carrier period in one access.
void synth_service(void)
{
    if (syn.pre->wave == WAVE_FLUTE) {
        synth_flute_service();
        return;
    }

    if (syn.pre->wave == WAVE_SQUARE || syn.pre->wave == WAVE_LASER ||
            !(prism_read32(PRISM_REG_CTRL) & PRISM_CTRL_INTERRUPT))
        return;

    uint32_t p;

    if (WAVE_IS_NOISE(syn.pre->wave)) {
        syn.lfsr = (syn.lfsr >> 1) ^ (-(syn.lfsr & 1) & 0xB400);
        p = (syn.base_p >> 5) +
            (((syn.base_p >> 5) * (uint32_t)(syn.lfsr & 0xFF)) >> 6);
    } else {
        syn.swap_phase ^= 1;
        p = syn.swap_phase ? syn.t_b : syn.t_a;
    }
    prism_write32(PRISM_REG_PRELOAD, p);
    prism_write8(PRISM_REG_HOST_TOGGLE, SYNTH_M);
}

// 1ms housekeeping: envelope -> comm (volume), vibrato and PWM sweep
void synth_tick(void)
{
    const synth_preset_t *pre = syn.pre;
    int pitch_dirty = 0;

    if (syn.gate_ms < 0xFFFF)
        ++syn.gate_ms;

    switch (syn.env_state) {
    case ENV_ATTACK:
        if (pre->attack == 0 || syn.level + pre->attack >= SYNTH_LVL_MAX) {
            syn.level = SYNTH_LVL_MAX;
            syn.env_state = ENV_DECAY;
        } else
            syn.level += pre->attack;
        break;
    case ENV_DECAY:
        if (syn.level > pre->sustain + pre->decay)
            syn.level -= pre->decay;
        else {
            syn.level = pre->sustain;
            // sustain 0 marks a one-shot (bell, drum, effects): done
            syn.env_state = pre->sustain ? ENV_SUSTAIN : ENV_IDLE;
        }
        break;
    case ENV_RELEASE:
        if (syn.level > pre->release)
            syn.level -= pre->release;
        else {
            syn.level = 0;
            syn.env_state = ENV_IDLE;
        }
        break;
    default:
        break;
    }

    // The flute voice owns the comm register (it shapes it per sample)
    if (pre->wave != WAVE_FLUTE)
        prism_comm_write(SYNTH_CENTER + (((syn.level >> 7) * syn.vel16) >> 4));

    // Sound effect pitch sweeps: the laser dives (and needs the preload
    // rewritten); the gun crack and explosion darken their noise, which
    // the swap interrupt service picks up from base_p by itself
    if (syn.env_state != ENV_IDLE &&
            (pre->wave == WAVE_LASER || WAVE_IS_NOISE(pre->wave)) &&
            pre->pw && syn.base_p < 4000000u) {
        syn.base_p += syn.base_p >> pre->pw;
        if (pre->wave == WAVE_LASER)
            pitch_dirty = 1;
    }

    // Flute pitch scoop: glide base_p down onto the target pitch
    if (pre->wave == WAVE_FLUTE && syn.base_p > syn.pitch_target) {
        uint32_t d = syn.base_p - syn.pitch_target;
        d = (d >> 5) + 1;
        syn.base_p = syn.base_p - d < syn.pitch_target ?
                     syn.pitch_target : syn.base_p - d;
        pitch_dirty = 1;
    }

    // Arpeggiator / duophony: rotate the sounding pitch through the cycle
    if (syn.arp_n > 1 && syn.env_state != ENV_IDLE &&
            ++syn.arp_tmr >= syn.arp_ms) {
        syn.arp_tmr = 0;
        if (++syn.arp_idx >= syn.arp_n)
            syn.arp_idx = 0;
        uint8_t n = syn.arp_note[syn.arp_idx];
        synth_set_pitch(n % 12, n / 12);
    }

    if (pre->vib_depth && syn.env_state != ENV_IDLE &&
            syn.gate_ms > pre->vib_delay) {
        if (++syn.vib_div >= pre->vib_rate) {
            syn.vib_div = 0;
            syn.vib_phase = (syn.vib_phase + 1) & 15;
            pitch_dirty = 1;
        }
    }

    if (pre->wave == WAVE_SWEEP && syn.env_state != ENV_IDLE) {
        syn.pw_cur += syn.pw_dir;
        if (syn.pw_cur >= 216)
            syn.pw_dir = -1;
        else if (syn.pw_cur <= 40)
            syn.pw_dir = 1;
        pitch_dirty = 1;
    }

    if (pitch_dirty)
        synth_apply_pitch();
}

static void synth_show_preset(void)
{
    note_out("[%s] ", syn.pre->name);
}

static int synth_key(int c)
{
    for (int i = 0; synth_keys_lo[i]; ++i)
        if (c == synth_keys_lo[i]) {
            synth_note_on(i, syn.octave);
            return 1;
        }
    for (int i = 0; synth_keys_hi[i]; ++i)
        if (c == synth_keys_hi[i]) {
            synth_note_on(i, syn.octave + 1);
            return 1;
        }

    switch (c) {
    case 'i':
        synth_note_on(0, syn.octave + 2);
        return 1;
    case ' ':
        synth_note_off();
        return 0;
    case '-':
        if (syn.octave > 1)
            --syn.octave;
        note_out("oct%d ", syn.octave);
        return 0;
    case '=':
        if (syn.octave < 6)
            ++syn.octave;
        note_out("oct%d ", syn.octave);
        return 0;
    case 'k':
        syn.duo = (uint8_t)((syn.duo + 1) % NUM_DUO);
        note_out("duo:%s ", synth_duo_name[syn.duo]);
        // Re-shape the sounding note with the new interval
        synth_set_arp(syn.arp_note[0], synth_duo_iv[syn.duo], SYNTH_DUO_MS);
        return 0;
    case 'o':
        syn.preset_idx = (syn.preset_idx + NUM_PRESETS - 1) % NUM_PRESETS;
        break;
    case 'p':
        syn.preset_idx = (syn.preset_idx + 1) % NUM_PRESETS;
        break;
    default:
        return 0;
    }

    // Preset changed
    syn.pre = &synth_presets[syn.preset_idx];
    synth_show_preset();
    if (syn.env_state != ENV_IDLE)
        synth_apply_pitch();
    return 0;
}
// Load the synth chroma and set up the engine.  Returns 0 on success.
static int synth_init(void)
{
    printf("\nLoading synth Chroma\n");

    // Stage sane register values first so the FSM starts up at the
    // pin's idle level (the fade after load brings it to silence)
    prism_set_count2_compare(SYNTH_M);
    prism_comm_write(1);
    prism_set_count1_preload(note_scaled(synth_note_p[0] >> 3)); // parked at C4

    int res = prism_load_chroma(chroma_synth, CHROMA_SYNTH_CTRL);

    chroma_set_loaded(chroma_synth);
    if (res) {
        printf("load FAILED, error mask 0x%05x\n", res);
        return res;
    }
    // fade the carrier up from the pin's idle level: no turn-on pop
    for (int d = 1; d <= SYNTH_CENTER; ++d) {
        prism_comm_write((uint8_t)d);
        uint32_t t0 = read_time();
        while (read_time() - t0 < us_ticks(300))
            ;
    }
    chroma_set_loaded(chroma_synth);

    prism_disable_interrupt();      // we poll; no ISR wanted
    prism_clear_interrupt();

    // Route the audio PMOD pin (uo_out[7]) to the PRISM
    set_gpio_func(7, 8);

    memset(&syn, 0, sizeof(syn));
    syn.preset_idx = 0;
    syn.pre = &synth_presets[0];
    syn.octave = 3;
    syn.pw_dir = 1;
    syn.pw_cur = 128;
    syn.lfsr = 0xACE1;
    syn.vel16 = 16;
    return 0;
}

void cmd_synth(int argc, char *argv[])
{
    if (argc > 1 && !strcmp(argv[1], "demo")) {
        uint32_t which = 1;
        if (argc > 2 && !parse_u32(argv[2], &which))
            return;
        if (which < 1 || which > (uint32_t)synth_demo_count()) {
            printf("demos:");
            for (int i = 0; i < synth_demo_count(); ++i)
                printf(" %d = %s%s", i + 1, synth_demo_name(i),
                       i < synth_demo_count() - 1 ? "," : "\n");
            return;
        }
        if (synth_init())
            return;
        synth_demo((int)which);
        prism_disable();
        return;
    }

    if (synth_init())
        return;

    printf(
"~~~ PRISM synth ~~~\n"
"  keys:  z s x d c v g b h n j m   = C..B (octave %d)\n"
"         q 2 w 3 e r 5 t 6 y 7 u   = C..B (octave %d), i = C%d\n"
"  - / =  octave down / up      o / p  previous / next preset\n"
"  k      duo mode (rapidly alternated 2nd voice: off/octave/fifth/third)\n"
"  space  release note          ESC or ` quits\n"
"  presets: ", syn.octave, syn.octave + 1, syn.octave + 2);
    for (int i = 0; i < NUM_PRESETS; ++i)
        printf("%s ", synth_presets[i].name);
    printf("\n\n");
    synth_show_preset();

    uint32_t next_tick = read_time() + us_ticks(1000);

    for (;;) {
        int c = uart_getc();

        if (c == 0x1b || c == '`')
            break;
        if (c != -1)
            synth_key(c);

        synth_service();

        if ((int32_t)(read_time() - next_tick) >= 0) {
            next_tick += us_ticks(1000);
            synth_tick();
        }
    }

    for (int d = SYNTH_CENTER; d >= 1; --d) {   // fade out, no pop
        prism_comm_write((uint8_t)d);
        uint32_t t0 = read_time();
        while (read_time() - t0 < us_ticks(300))
            ;
    }
    prism_disable();        // resets the FSM: output low, silent
    printf("\nsynth off\n");
}

// ==========================================================================
// Polyphonic PWL synth ('synthp' command), in the spirit of the
// PiecewiseOrionSynth peripheral: three voices with piecewise linear
// waveforms (saw / triangle), a shift-based brightness control that acts
// like the PWL slope (clamped scaling morphs towards square = brighter),
// and per-voice decay envelopes, all summed in software at 15625Hz and
// played through the PCM chroma's 8-bit PWM DAC (prism_isr.s mode 2, same
// ping-pong machinery as ADPCM playback).  Budget: ~70 instructions per
// sample against a 65.5ms buffer budget - it fits at 64MHz.
// ==========================================================================

#define POLY_VOICES     4               // 4th voice only at >=85MHz
int poly_nvoices = 3;
int poly_drum_voice = -1;   // the MIDI player reserves the last voice
                            // for the kit when the song has drums
#define POLY_BLOCK      1024u           // samples per ping-pong buffer
#define POLY_RATE       12500u          // internal render rate the note
                                        //   step table is referenced to
#define POLY_OUT_HZ     25000u          // 2x-interpolated OUTPUT rate

// 'synthp -i': the renderer computes 12500Hz samples but the output
// stream runs at double rate with a linear-interpolated midpoint
// between each pair, pushing the zero-order-hold images from ~12.3kHz
// (audible whistles) to ~25kHz (ultrasonic).  Off (default) streams
// the rendered samples directly at ~12.5kHz.
int poly_interp;

// Clocks per OUTPUT sample: nearest whole number of 256-clock
// carriers (same rule as the ADPCM player).  At 64MHz both modes are
// exact: 2560 clocks (25000Hz) / 5120 clocks (12500Hz).
static uint32_t poly_out_period(void)
{
    uint32_t rate = poly_interp ? POLY_OUT_HZ : POLY_RATE;
    uint32_t period = (clock_hz + rate / 2) / rate;

    return ((period + 128u) / 256u) * 256u;
}

// count1 preload (the FSM adds its 64-clock offset back)
static uint32_t poly_preload(void)
{
    return poly_out_period() - 64u;
}

// Q16 note-step correction: the grid-rounded output rate makes the
// REAL internal rate clock_hz/(2*period) instead of 12500; scaling
// each note's step by 12500/internal cancels it exactly, so absolute
// pitch is spot on at ANY clock (identity, 65536, at 64MHz).
static uint32_t poly_step_scale = 65536u;

struct poly_voice {
    uint32_t phase;
    uint32_t step;                      // frequency as phase/sample
    uint8_t  level;                     // envelope 0..31
    int8_t   ramp;                      // +1 attack / -1 release, one level
                                        //   per 8 samples (~20ms 0..full):
                                        //   soft edges, no speaker pop
    uint8_t  decay_div;
    uint8_t  vocal;                     // melody voice: protected from
                                        //   accompaniment stealing
    uint8_t  inst;                      // instrument (poly_presets index)
    uint16_t lfsr;                      // noise state (tri == 2 presets)
    uint8_t  peak;                      // velocity peak level 24..31
    uint16_t gate;                      // chunks until auto note-off (0 off)
    uint32_t step_tgt;                  // real pitch (slide/vibrato center)
    int32_t  slide_inc;                 // pitch env: step delta per chunk
    uint16_t slide_n;                   // chunks of slide left
    uint16_t vib_wait;                  // chunks before the LFO starts
    int32_t  vib_pos, vib_inc, vib_dev; // triangle LFO state (step units)
};

typedef struct {
    const char *name;
    uint8_t tri;                        // 0 = saw, 1 = tri, 2 = LFSR noise
    uint8_t bright;                     // clamp-morph shift 0..3
    // amp ADSR on the 31-level ladder (~3dB per level):
    uint8_t a_mask;                     // attack: 2^k-1 samples per level
    uint8_t decay;                      // decay: chunks (5.1ms) per level
    uint8_t sus;                        // sustain level (0 = ring out)
    uint8_t r_mask;                     // release samples-per-level mask
    uint16_t gate_ms;                   // auto note-off (0 = hold/ring)
    // pitch envelope: start p_off semitones away, slide home over
    // p_ms8*8 ms (PWL-style scoop/grace)
    int8_t  p_off;
    uint8_t p_ms8;
    // vibrato triangle LFO: the held-note modulator
    uint8_t v_rate;                     // Hz*2
    uint8_t v_cents;                    // peak deviation (0 = off)
    uint16_t v_delay_ms;                // onset delay
} poly_preset_t;

static const poly_preset_t poly_presets[] = {
    //                      A   D  S   R  gate  penv   vibrato
    { "strings", 0, 0,     31, 24, 22, 15,   0, 0, 0,  9, 10, 350 },
    { "brite",   0, 2,      1, 12, 24,  7,   0, 0, 0,  0,  0,   0 },
    { "nes",     1, 0,      1,  8,  0,  3,   0, 0, 0,  0,  0,   0 },
    { "organ",   1, 1,      1, 56,  0,  7,   0, 0, 0,  0,  0,   0 },
    { "piano",   0, 1,      1, 10,  0,  3,   0, 0, 0,  0,  0,   0 },
    { "brass",   0, 2,      7, 20, 26,  7, 500, -2, 8, 0,  0,   0 },
    { "flute",   1, 0,     15, 30, 26,  7, 600, 0, 0, 10, 16, 300 },
    // The drum kit: kick is a triangle dropping ~an octave into its
    // pitch, snare and hat are white LFSR noise with only the envelope
    // (and the MIDI mapper's gate) telling them apart.
    { "kick",    1, 0,      1,  1,  0,  3,  90, 14, 6, 0,  0,   0 },
    { "snare",   2, 0,      1,  1,  0,  7, 110, 0, 0, 0,  0,   0 },
    { "hat",     2, 0,      1,  1,  0,  3,  30, 0, 0, 0,  0,   0 },
};
#define NUM_POLY_INST \
    ((int)(sizeof(poly_presets) / sizeof(poly_presets[0])))

const char *poly_inst_name(int idx)
{
    return (idx >= 0 && idx < NUM_POLY_INST) ? poly_presets[idx].name : "?";
}

int poly_inst_find(const char *name)
{
    for (int i = 0; i < NUM_POLY_INST; ++i)
        if (strcasecmp(poly_presets[i].name, name) == 0)
            return i;
    return -1;
}

int poly_inst_count(void)
{
    return NUM_POLY_INST;
}
#define NUM_POLY_PRESETS \
    ((int)(sizeof(poly_presets) / sizeof(poly_presets[0])))

static struct poly_voice poly_v[POLY_VOICES];
void (*poly_note_out2)(int voice, const char *text);
static uint8_t poly_buf[2][2u * POLY_BLOCK] __attribute__((aligned(4)));
int poly_preset;

// Envelope scaling without multiplies: a uniform ~3dB ladder (6dB shift
// per two levels, x0.75 half-steps between)
static inline int32_t poly_env(int32_t v, uint32_t lv)
{
    uint32_t a = 31 - lv;

    v >>= a >> 1;
    if (a & 1)
        v -= v >> 2;
    return v;
}

// Render one buffer of summed voices; returns nonzero if any voice is
// sounding.  Voice-major: each voice's state stays in registers for the
// whole block (struct accesses per sample were the previous version's
// downfall - 101ms per block; this one fits the budget), sweeping a mix
// buffer that a final pass converts to PWM duty bytes.
static int32_t poly_mix[POLY_BLOCK];

static uint32_t poly_render(uint8_t *dst)
{
    int wrote = 0;

    for (int nv = 0; nv < poly_nvoices; ++nv) {
        struct poly_voice *v = &poly_v[nv];

        if (!v->level && !v->ramp)
            continue;
        // Envelope rates and waveform come from the VOICE's instrument,
        // so a MIDI melody, bass and drums can sound at once
        const poly_preset_t *pre = &poly_presets[v->inst];
        const int tri = pre->tri == 1;
        const int noise = pre->tri == 2;
        const int bright = pre->bright;
        const uint32_t decay = pre->decay;
        uint32_t lfsr = v->lfsr ? v->lfsr : 0xACE1u;
        uint32_t phase = v->phase, step = v->step;
        uint32_t lv = v->level, div = v->decay_div;
        uint32_t peak = v->peak ? v->peak : 31u;
        uint32_t sus = pre->sus;
        int32_t *mp = poly_mix;

        int32_t ramp = v->ramp;
        // Attack/release stepping rates come from the instrument (2^k-1
        // samples per ladder level); attacks still SPEAK, but a pad can
        // now swell and a release can linger.
        uint32_t rmask = (ramp > 0) ? pre->a_mask : pre->r_mask;

        for (uint32_t chunk = 0; chunk < POLY_BLOCK / 64; ++chunk, mp += 64) {
            if (!lv && !ramp) {         // idle / released
                if (!wrote)
                    memset(mp, 0, 64 * sizeof(*mp));
                continue;
            }
            // Chunk-rate modulators (5.1ms): pitch slide home, then the
            // vibrato triangle around the landed pitch, and the gate
            // clock that turns note-on into a timed note-off.
            if (v->slide_n) {
                step += (uint32_t)v->slide_inc;
                if (!--v->slide_n)
                    step = v->step_tgt;
            } else if (v->vib_dev) {
                if (v->vib_wait)
                    --v->vib_wait;
                else {
                    v->vib_pos += v->vib_inc;
                    if (v->vib_pos > v->vib_dev || v->vib_pos < -v->vib_dev) {
                        v->vib_inc = -v->vib_inc;
                        v->vib_pos += 2 * v->vib_inc;
                    }
                    step = (uint32_t)((int32_t)v->step_tgt + v->vib_pos);
                }
            }
            if (v->gate && !--v->gate) {
                ramp = -1;              // gate elapsed: release stage
                rmask = pre->r_mask;
            }
            if (ramp) {
                // attack or release stepping, rate set by rmask above
                for (uint32_t i = 0; i < 64; ++i) {
                    phase += step;
                    int32_t s;
                    if (noise) {
                        lfsr = (lfsr >> 1) ^ ((0u - (lfsr & 1u)) & 0xB400u);
                        s = (int16_t)lfsr;
                    } else {
                        s = (int32_t)(phase >> 16) - 32768;
                        if (tri) {
                            int32_t a = s >> 31;
                            s = 32767 - (((s ^ a) - a) << 1);
                        }
                        s <<= bright;
                        if (s > 32767) s = 32767;
                        else if (s < -32768) s = -32768;
                    }
                    s = poly_env(s, lv);
                    if (wrote)
                        mp[i] += s;
                    else
                        mp[i] = s;
                    if ((i & rmask) == rmask) {
                        int32_t nl = (int32_t)lv + ramp;
                        if (ramp > 0 && nl >= (int32_t)peak) {
                            lv = peak; ramp = 0;
                        }
                        else if (nl <= 0) { lv = 0; ramp = 0; }
                        else lv = (uint32_t)nl;
                    }
                }
            } else {
                for (uint32_t i = 0; i < 64; ++i) {
                    phase += step;
                    int32_t s;
                    if (noise) {                                    // drums
                        lfsr = (lfsr >> 1) ^ ((0u - (lfsr & 1u)) & 0xB400u);
                        s = (int16_t)lfsr;
                    } else {
                    s = (int32_t)(phase >> 16) - 32768;             // saw
                    if (tri) {
                        int32_t a = s >> 31;                        // triangle
                        s = 32767 - (((s ^ a) - a) << 1);
                    }
                    s <<= bright;                                   // PWL slope
                    if (s > 32767) s = 32767;                       // clamp
                    else if (s < -32768) s = -32768;
                    }
                    s = poly_env(s, lv);
                    if (wrote)
                        mp[i] += s;
                    else
                        mp[i] = s;
                }
                if (++div >= decay) {   // decay toward sustain, per
                    div = 0;                // chunk (sus 0 = ring out)
                    if (lv > sus)
                        --lv;
                }
            }
        }
        v->phase = phase;
        v->step = step;                 // slides advance it per chunk
        v->lfsr = (uint16_t)lfsr;
        v->level = (uint8_t)lv;
        v->ramp = (int8_t)ramp;
        v->decay_div = (uint8_t)div;
        wrote = 1;
    }

    static int32_t last = 128;          // previous block's final duty,
                                        //   for the seam midpoint
    if (!wrote) {
        memset(dst, 128, (poly_interp ? 2u : 1u) * POLY_BLOCK);
        last = 128;
        return 0;
    }
    // The output buffers live in PSRAM where every store is a bus
    // transaction (~us each, not ns) - at 64MHz the interpolated
    // byte-by-byte emit alone cost more than the refill slack and
    // popped audibly (83.1ms render vs the 81.9ms budget, 153
    // underruns in 15s of demo 2).  Packing four duty bytes per
    // 32-bit store cuts those transactions 4x; dst is 4-aligned and
    // POLY_BLOCK a multiple of 4.
    uint32_t *wd = (uint32_t *)(void *)dst;

    if (!poly_interp) {
        for (uint32_t i = 0; i < POLY_BLOCK; i += 4) {
            uint32_t w = 0;

            for (uint32_t k = 0; k < 4; ++k) {
                int32_t d = 128 + (poly_mix[i + k] >> 10);

                if (d < 1) d = 1;
                else if (d > 253) d = 253;
                w |= (uint32_t)d << (8 * k);
            }
            *wd++ = w;
        }
        return 1;
    }
    for (uint32_t i = 0; i < POLY_BLOCK; i += 2) {
        int32_t d0 = 128 + (poly_mix[i] >> 10);
        int32_t d1 = 128 + (poly_mix[i + 1] >> 10);

        if (d0 < 1) d0 = 1;
        else if (d0 > 253) d0 = 253;
        if (d1 < 1) d1 = 1;
        else if (d1 > 253) d1 = 253;
        *wd++ = (uint32_t)((last + d0) >> 1)            // midpoints
              | ((uint32_t)d0 << 8)
              | ((uint32_t)((d0 + d1) >> 1) << 16)
              | ((uint32_t)d1 << 24);
        last = d1;
    }
    return 1;
}

int poly_note_on_ex(int semi, int oct, int vocal, int vel, int inst)
{
    if (oct < 1) oct = 1;
    if (oct > 6) oct = 6;                       // keep under Nyquist

    // phase step: f / 12500 in 32.32; with P = 32e6/f this is exactly
    // (2560 << 32) / P
    // RAW 64MHz-referenced half period: poly_step_scale maps the step
    // to the real internal rate on its own - note_scaled() here too
    // was double clock scaling (-5 semitones at 85MHz)
    uint32_t p = synth_note_p[semi] >> (oct - 1);

    // Voice selection with melody protection (PD_V):
    //   1. an idle voice
    //   2. the quietest accompaniment voice (smallest cut, musically
    //      the most decayed note)
    //   3. vocal notes only: the quietest vocal voice
    // An accompaniment strike never steals a still-ringing vocal voice;
    // with none available it is dropped so the melody holds its full
    // length.  At most two voices stay vocal at once (a new melody note
    // then recycles the older melody line) so accompaniment always has
    // at least one voice to cycle through.
    struct poly_voice *idle = NULL, *acc = NULL, *voc = NULL;
    struct poly_voice *v;
    int nvoc = 0;

    if (poly_drum_voice >= 0 && inst >= POLY_I_KICK) {
        v = &poly_v[poly_drum_voice];   // the kit owns its voice: a hit
        goto take;                      // simply replaces what rings
    }
    for (int nv = 0; nv < poly_nvoices; ++nv) {
        struct poly_voice *c = &poly_v[nv];

        if (nv == poly_drum_voice)
            continue;                   // reserved for the kit
        if (!c->level) {                // idle (render zeroes ramp too)
            if (idle == NULL)
                idle = c;
        } else if (c->vocal) {
            ++nvoc;
            if (voc == NULL || c->level < voc->level)
                voc = c;
        } else {
            if (acc == NULL || c->level < acc->level)
                acc = c;
        }
    }
    if (vocal && nvoc >= 2)
        v = voc;                        // recycle the older melody line
    else if (idle != NULL)
        v = idle;
    else if (acc != NULL)
        v = acc;
    else if (vocal)
        v = voc;
    else
        return -1;                      // all voices vocal: drop accomp.
take:
    v->vocal = (uint8_t)vocal;
    v->inst = (uint8_t)inst;

    v->step = (uint32_t)((2560ULL << 32) / p);
    v->step = (uint32_t)(((uint64_t)v->step * poly_step_scale) >> 16);
    v->step_tgt = v->step;

    // Instrument modulators (all chunk-rate; ~205/1024 chunks per ms)
    const poly_preset_t *in = &poly_presets[inst];

    v->slide_n = 0;
    v->vib_dev = 0;
    v->vib_pos = 0;
    if (in->p_off) {                    // scoop/grace: start offset
        int s2 = semi + in->p_off, o2 = oct;

        while (s2 < 0)   { s2 += 12; --o2; }
        while (s2 >= 12) { s2 -= 12; ++o2; }
        if (o2 < 1) o2 = 1;
        if (o2 > 6) o2 = 6;
        uint32_t p2 = synth_note_p[s2] >> (o2 - 1);
        uint32_t st = (uint32_t)((2560ULL << 32) / p2);
        uint32_t n = ((uint32_t)in->p_ms8 * 8u * 205u) >> 10;

        st = (uint32_t)(((uint64_t)st * poly_step_scale) >> 16);
        if (n == 0)
            n = 1;
        v->slide_inc = (int32_t)(v->step_tgt - st) / (int32_t)n;
        v->slide_n = (uint16_t)n;
        v->step = st;
    }
    if (in->v_cents) {                  // vibrato: dev in step units,
        v->vib_dev = (int32_t)(((uint64_t)v->step_tgt * in->v_cents)
                               / 1731u);
        v->vib_inc = (int32_t)(((int64_t)v->vib_dev * in->v_rate) / 98);
        if (v->vib_inc == 0)
            v->vib_inc = 1;
        v->vib_wait = (uint16_t)(((uint32_t)in->v_delay_ms * 205u) >> 10);
    }
    v->gate = (uint16_t)(((uint32_t)in->gate_ms * 205u) >> 10);
    v->peak = (uint8_t)(31u - ((127u - ((uint32_t)vel & 127u)) >> 4));
    // start at the waveform's zero crossing so the first samples are
    // near silent and the soft attack does the rest
    v->phase = in->tri ? 0x40000000u : 0x80000000u;
    // Skip the inaudible bottom of the ladder (levels 1..11 are below
    // -60dB): starting at 12 plus the 2-sample attack rate puts the
    // note at full level in ~3ms instead of ~20ms, so the organ speaks
    // on the beat.  The zero-crossing phase start keeps the onset
    // pop-free even at this rate.
    v->level = 12;
    v->ramp = 1;                        // ~3ms attack (see rmask)
    v->decay_div = 0;
    // Melody (PD_V) notes print in bright yellow: raw ANSI on the plain
    // console; the TUI's Notes tab translates the same escapes into
    // curses attributes at draw time.
    {
        char tok[8];

        if (inst == POLY_I_KICK)
            tok[0] = 'K', tok[1] = 0;
        else if (inst == POLY_I_SNARE)
            tok[0] = 'S', tok[1] = 0;
        else if (inst == POLY_I_HAT)
            tok[0] = 'H', tok[1] = 0;
        else
            snprintf(tok, sizeof(tok), "%s%d", synth_note_name[semi], oct);
        if (poly_note_out2)             // TUI voice tracks
            poly_note_out2((int)(v - poly_v), tok);
        else if (vocal)
            note_out("\x1b[93m%s\x1b[0m ", tok);
        else
            note_out("%s ", tok);
    }
    return (int)(v - poly_v);
}

void poly_voice_gate(int vi, uint32_t ms)
{
    if (vi >= 0 && vi < poly_nvoices)
        poly_v[vi].gate = (uint16_t)((ms * 205u) >> 10);
}

int poly_active(void)
{
    for (int nv = 0; nv < poly_nvoices; ++nv)
        if (poly_v[nv].level || poly_v[nv].ramp)
            return 1;
    return 0;
}

static void poly_note_on(int semi, int oct)
{
    poly_note_on_ex(semi, oct, 0, 118, poly_preset);
}

static int poly_key(int c)
{
    for (int i = 0; synth_keys_lo[i]; ++i)
        if (c == synth_keys_lo[i]) {
            poly_note_on(i, syn.octave);
            return 1;
        }
    for (int i = 0; synth_keys_hi[i]; ++i)
        if (c == synth_keys_hi[i]) {
            poly_note_on(i, syn.octave + 1);
            return 1;
        }

    switch (c) {
    case '-':
        if (syn.octave > 1) --syn.octave;
        note_out("oct%d ", syn.octave);
        break;
    case '=':
        if (syn.octave < 5) ++syn.octave;
        note_out("oct%d ", syn.octave);
        break;
    case ' ':
        for (int nv = 0; nv < poly_nvoices; ++nv)
            if (poly_v[nv].level)
                poly_v[nv].ramp = -1;   // soft release, no pop
        break;
    case 'o':
        poly_preset = (poly_preset + NUM_POLY_PRESETS - 1) % NUM_POLY_PRESETS;
        note_out("[%s] ", poly_presets[poly_preset].name);
        break;
    case 'p':
        poly_preset = (poly_preset + 1) % NUM_POLY_PRESETS;
        note_out("[%s] ", poly_presets[poly_preset].name);
        break;
    }
    return 0;
}

// ==========================================================================
// Organ demo ('synthp demo'): a Toccata-in-D-minor style opening for the
// 'organ' preset - mordents and runs blur into the ~5s ring like
// cathedral acoustics, rolled chords sustain into real 3-voice harmony,
// and PD_DAMP events lift the organist's hands so held resolutions don't
// clash with ringing neighbours.  Loops until any key is pressed.
// ==========================================================================

#define PD_DAMP  0xFF                   // n[0]: silence all voices

// "Vocal" (melody / treble clef) flag, OR'd onto a note byte in the
// table: the voice it lands on is protected - accompaniment strikes
// never steal it while it still rings (they are dropped instead), so
// the melody holds its full length no matter how busy the other lines
// get.  Only another PD_V note (or PD_DAMP / natural decay) takes the
// voice back.  Note values only reach 83, so bit 7 is free (PD_DAMP =
// 0xFF is checked first).
#define PD_V     0x80

struct pdemo_ev {
    uint8_t n[3];                       // up to 3 notes struck together
                                        //   (PD_V marks a melody note)
    uint8_t len;                        // steps of 80ms; 0 = end of song
};

/*
static const struct pdemo_ev pdemo_organ[] = {
    // Statement 1 (high): mordent, held A, run, leading tone, resolution
    { {nA(5), 0, 0}, 1 },  { {nG(5), 0, 0}, 1 },  { {nA(5), 0, 0}, 8 },
    { {PD_DAMP, 0, 0}, 1 },
    { {nG(5), 0, 0}, 1 },  { {nF(5), 0, 0}, 1 },
    { {nE(5), 0, 0}, 1 },  { {nD(5), 0, 0}, 1 },
    { {PD_DAMP, 0, 0}, 1 },
    { {nCs(5), 0, 0}, 6 },
    { {PD_DAMP, 0, 0}, 1 },
    { {nD(5), 0, 0}, 14 },
    { {PD_DAMP, 0, 0}, 4 },
    // Statement 2, an octave down
    { {nA(4), 0, 0}, 1 },  { {nG(4), 0, 0}, 1 },  { {nA(4), 0, 0}, 8 },
    { {PD_DAMP, 0, 0}, 1 },
    { {nG(4), 0, 0}, 1 },  { {nF(4), 0, 0}, 1 },
    { {nE(4), 0, 0}, 1 },  { {nD(4), 0, 0}, 1 },
    { {PD_DAMP, 0, 0}, 1 },
    { {nCs(4), 0, 0}, 6 },
    { {PD_DAMP, 0, 0}, 1 },
    { {nD(4), 0, 0}, 14 },
    { {PD_DAMP, 0, 0}, 4 },
    // Statement 3, low
    { {nA(3), 0, 0}, 1 },  { {nG(3), 0, 0}, 1 },  { {nA(3), 0, 0}, 8 },
    { {PD_DAMP, 0, 0}, 1 },
    { {nG(3), 0, 0}, 1 },  { {nF(3), 0, 0}, 1 },
    { {nE(3), 0, 0}, 1 },  { {nD(3), 0, 0}, 1 },
    { {PD_DAMP, 0, 0}, 1 },
    { {nCs(3), 0, 0}, 6 },
    { {PD_DAMP, 0, 0}, 1 },
    { {nD(3), 0, 0}, 12 },
    { {PD_DAMP, 0, 0}, 2 },
    // The rolled diminished chord - each note rings under the next
    { {nCs(4), 0, 0}, 3 }, { {nE(4), 0, 0}, 3 },
    { {nG(4), 0, 0}, 3 },  { {nAs(4), 0, 0}, 12 },
    { {PD_DAMP, 0, 0}, 2 },
    // Resolution: open fifth swell, then the D major (Picardy) close
    { {nD(3), nA(3), nD(4)}, 16 },
    { {PD_DAMP, 0, 0}, 1 },
    { {nD(2), nA(3), nFs(4)}, 28 },
    { {PD_DAMP, 0, 0}, 6 },
    { {0, 0, 0}, 0 },
};
*/

// ==========================================================================
// "Floating Lanterns"
//
// Soothing, handpan / tubular-bell style piece for the PRISM PCM poly synth.
//
// Designed around:
//   - 3 independent ringing voices
//   - ~5 second natural decay
//   - 80 ms sequencer step
//   - notes being allowed to ring into following notes
//
// Tonal center: D major / B minor
//
// Main palette:
//
//      D  E  F#  A  B
//
// Mostly D-major pentatonic.  C# and G appear selectively to establish
// harmony, but close dissonances are intentionally avoided because the
// long ringing tails cause neighbouring notes to overlap.
//
// Harmonic language:
//
//      D(add2) | Bm | G | Asus2 / A
//
// Open voicings are favored:
//
//      Dadd2 : D3 A3 E4
//      D     : D3 A3 F#4
//      Bm    : B2 F#3 D4
//      G     : G2 D3 B3
//      Asus2 : A2 E3 B3
//      A     : A2 E3 C#4
//
// PD_DAMP is used sparingly.  Most of the time the previous tones are
// deliberately allowed to decay underneath the next strikes.
//
// At 80 ms/step this is roughly a minute-plus piece before looping.
// ==========================================================================

static const struct pdemo_ev pdemo_lanterns[] = {

    // ======================================================================
    // I. FIRST LIGHT
    //
    // Individual bell tones appear slowly.  Establish the five-note
    // vocabulary before exposing the harmony.
    // ======================================================================

    { {PD_DAMP, 0, 0}, 4 },

    { {nD(4),  0, 0}, 10 },
    { {nA(4),  0, 0},  8 },
    { {nE(5),  0, 0}, 12 },

    { {nFs(4), 0, 0},  8 },
    { {nA(4),  0, 0},  8 },
    { {nD(5),  0, 0}, 16 },

    { {nB(4),  0, 0},  8 },
    { {nA(4),  0, 0},  8 },
    { {nFs(4), 0, 0}, 10 },
    { {nE(4),  0, 0},  8 },
    { {nD(4),  0, 0}, 18 },

    { {PD_DAMP, 0, 0}, 5 },


    // ======================================================================
    // II. THE FIRST LANTERN
    //
    // First real three-note sonority.
    //
    // Dadd2 gives the instrument a spacious suspended quality instead of
    // immediately declaring a conventional major chord.
    // ======================================================================

    { {nD(3), nA(3), nE(4)}, 18 },

    { {nFs(4), 0, 0}, 6 },
    { {nA(4),  0, 0}, 6 },
    { {nD(5),  0, 0}, 12 },

    { {nA(3), nE(4), nB(4)}, 16 },

    { {nA(4),  0, 0}, 6 },
    { {nFs(4), 0, 0}, 6 },
    { {nE(4),  0, 0}, 8 },
    { {nD(4),  0, 0}, 14 },


    // Let the sound disappear naturally.
    { {PD_DAMP, 0, 0}, 5 },


    // ======================================================================
    // III. GENTLE CURRENT
    //
    // D -> Bm -> G -> A
    //
    // Each chord is followed by a tiny melodic answer.  The chord tails
    // should blend into those notes rather than behaving like block chords.
    // ======================================================================

    // D
    { {nD(3), nA(3), nFs(4)}, 14 },
    { {nA(4), 0, 0},  5 },
    { {nB(4), 0, 0},  5 },
    { {nA(4), 0, 0},  8 },

    // B minor
    { {nB(2), nFs(3), nD(4)}, 14 },
    { {nFs(4), 0, 0}, 5 },
    { {nE(4),  0, 0}, 5 },
    { {nD(4),  0, 0}, 8 },

    // G
    { {nG(2), nD(3), nB(3)}, 14 },
    { {nD(4), 0, 0}, 5 },
    { {nE(4), 0, 0}, 5 },
    { {nFs(4),0, 0}, 8 },

    // Asus2
    { {nA(2), nE(3), nB(3)}, 14 },
    { {nE(4),  0, 0}, 5 },
    { {nFs(4), 0, 0}, 5 },
    { {nA(4),  0, 0}, 10 },


    // ======================================================================
    // IV. FLOATING MOTIF
    //
    // Main melody:
    //
    //      F# A B A | E F# D
    //
    // It is intentionally simple.  The ringing instrument supplies much
    // of the apparent complexity.
    // ======================================================================

    { {PD_DAMP, 0, 0}, 3 },

    { {nD(3), nA(3), nE(4)}, 12 },

    { {nFs(4), 0, 0}, 6 },
    { {nA(4),  0, 0}, 6 },
    { {nB(4),  0, 0}, 8 },
    { {nA(4),  0, 0}, 8 },

    { {nE(4),  0, 0}, 6 },
    { {nFs(4), 0, 0}, 6 },
    { {nD(4),  0, 0}, 14 },


    // Answer, slightly higher.
    { {nB(2), nFs(3), nD(4)}, 12 },

    { {nA(4),  0, 0}, 6 },
    { {nB(4),  0, 0}, 6 },
    { {nD(5),  0, 0}, 8 },
    { {nB(4),  0, 0}, 8 },

    { {nFs(4), 0, 0}, 6 },
    { {nE(4),  0, 0}, 6 },
    { {nD(4),  0, 0}, 14 },


    // ======================================================================
    // V. RIPPLES
    //
    // Rolled chords.  The 3-voice engine should make these especially
    // effective because each note begins separately but all three ring.
    // ======================================================================

    { {PD_DAMP, 0, 0}, 4 },

    // Rolled Dadd2
    { {nD(3),  0, 0}, 4 },
    { {nA(3),  0, 0}, 4 },
    { {nE(4),  0, 0}, 14 },

    // Small reflection
    { {nFs(4), 0, 0}, 5 },
    { {nA(4),  0, 0}, 9 },


    // Rolled Bm
    { {nB(2),  0, 0}, 4 },
    { {nFs(3), 0, 0}, 4 },
    { {nD(4),  0, 0}, 14 },

    { {nFs(4), 0, 0}, 5 },
    { {nE(4),  0, 0}, 9 },


    // Rolled G
    { {nG(2),  0, 0}, 4 },
    { {nD(3),  0, 0}, 4 },
    { {nB(3),  0, 0}, 14 },

    { {nD(4), 0, 0}, 5 },
    { {nFs(4),0, 0}, 9 },


    // Rolled Asus2
    { {nA(2),  0, 0}, 4 },
    { {nE(3),  0, 0}, 4 },
    { {nB(3),  0, 0}, 14 },

    { {nE(4), 0, 0}, 5 },
    { {nA(4), 0, 0}, 12 },


    // ======================================================================
    // VI. WARM WATER
    //
    // The harmony brightens.  Full triads become more common, but there
    // is still space between them.
    // ======================================================================

    { {PD_DAMP, 0, 0}, 3 },

    { {nG(2), nD(3), nB(3)}, 16 },

    { {nB(4),  0, 0}, 6 },
    { {nA(4),  0, 0}, 6 },
    { {nFs(4), 0, 0}, 10 },


    { {nD(3), nA(3), nFs(4)}, 16 },

    { {nE(4),  0, 0}, 6 },
    { {nFs(4), 0, 0}, 6 },
    { {nA(4),  0, 0}, 10 },


    { {nB(2), nFs(3), nD(4)}, 16 },

    { {nD(5), 0, 0}, 6 },
    { {nB(4), 0, 0}, 6 },
    { {nA(4), 0, 0}, 10 },


    // A major rather than suspended A provides a gentle sense of movement.
    { {nA(2), nE(3), nCs(4)}, 16 },

    { {nE(4),  0, 0}, 6 },
    { {nFs(4), 0, 0}, 6 },
    { {nA(4),  0, 0}, 12 },


    // ======================================================================
    // VII. SECOND LANTERN
    //
    // Main motif returns one octave higher.
    // ======================================================================

    { {PD_DAMP, 0, 0}, 4 },

    { {nD(3), nA(3), nE(4)}, 12 },

    { {nFs(5), 0, 0}, 6 },
    { {nA(5),  0, 0}, 6 },
    { {nB(5),  0, 0}, 8 },
    { {nA(5),  0, 0}, 8 },

    { {nE(5),  0, 0}, 6 },
    { {nFs(5), 0, 0}, 6 },
    { {nD(5),  0, 0}, 14 },


    // Let a full D chord answer the high melody.
    { {nD(3), nA(3), nFs(4)}, 18 },


    { {nA(4),  0, 0}, 6 },
    { {nB(4),  0, 0}, 6 },
    { {nD(5),  0, 0}, 8 },
    { {nE(5),  0, 0}, 8 },
    { {nFs(5), 0, 0}, 10 },
    { {nA(5),  0, 0}, 14 },


    // ======================================================================
    // VIII. OPEN SKY
    //
    // The most explicitly polyphonic section.
    //
    // Slow three-note chord changes allow the tubular-bell quality to
    // become the focus of the piece.
    // ======================================================================

    { {PD_DAMP, 0, 0}, 4 },

    { {nD(3), nA(3), nFs(4)}, 20 },

    { {nB(2), nFs(3), nD(4)}, 20 },

    { {nG(2), nD(3), nB(3)}, 20 },

    { {nA(2), nE(3), nB(3)}, 20 },


    // Second pass, different inversions/registers.

    { {nD(3), nE(4), nA(4)}, 20 },

    { {nB(2), nD(4), nFs(4)}, 20 },

    { {nG(2), nB(3), nD(4)}, 20 },

    { {nA(2), nCs(4), nE(4)}, 22 },


    // ======================================================================
    // IX. LITTLE STARS
    //
    // A short sequence of isolated high notes over implied harmony.
    // This should feel almost like drops landing on a steel tongue drum.
    // ======================================================================

    { {PD_DAMP, 0, 0}, 4 },

    { {nD(4), nA(4), 0}, 10 },

    { {nE(5),  0, 0}, 7 },
    { {nA(5),  0, 0}, 7 },
    { {nFs(5), 0, 0}, 10 },

    { {nB(3), nFs(4), 0}, 10 },

    { {nD(5), 0, 0}, 7 },
    { {nFs(5),0, 0}, 7 },
    { {nA(5), 0, 0}, 10 },

    { {nG(3), nD(4), 0}, 10 },

    { {nB(4), 0, 0}, 7 },
    { {nA(4), 0, 0}, 7 },
    { {nFs(4),0, 0}, 10 },

    { {nA(3), nE(4), 0}, 10 },

    { {nE(5), 0, 0}, 7 },
    { {nFs(5),0, 0}, 7 },
    { {nA(5), 0, 0}, 12 },


    // ======================================================================
    // X. HOMEWARD
    //
    // Return to the original register and progressively simplify.
    // ======================================================================

    { {PD_DAMP, 0, 0}, 4 },

    { {nD(3), nA(3), nE(4)}, 16 },

    { {nFs(4), 0, 0}, 6 },
    { {nA(4),  0, 0}, 6 },
    { {nB(4),  0, 0}, 8 },
    { {nA(4),  0, 0}, 8 },
    { {nFs(4), 0, 0}, 8 },
    { {nE(4),  0, 0}, 8 },
    { {nD(4),  0, 0}, 14 },


    { {nG(2), nD(3), nB(3)}, 16 },

    { {nB(4),  0, 0}, 6 },
    { {nA(4),  0, 0}, 6 },
    { {nFs(4), 0, 0}, 8 },
    { {nE(4),  0, 0}, 8 },


    { {nA(2), nE(3), nCs(4)}, 18 },

    { {nE(4),  0, 0}, 6 },
    { {nFs(4), 0, 0}, 6 },
    { {nA(4),  0, 0}, 10 },


    // ======================================================================
    // XI. LAST LANTERNS
    //
    // The final progression is extremely slow.
    // ======================================================================

    { {PD_DAMP, 0, 0}, 5 },

    { {nB(2), nFs(3), nD(4)}, 22 },

    { {nG(2), nD(3), nB(3)}, 22 },

    { {nA(2), nE(3), nB(3)}, 22 },


    // The suspended dominant quietly resolves into D.
    { {PD_DAMP, 0, 0}, 3 },

    { {nA(2), nE(3), nCs(4)}, 18 },

    { {PD_DAMP, 0, 0}, 2 },

    { {nD(3), nA(3), nFs(4)}, 28 },


    // ======================================================================
    // XII. CODA
    //
    // Strip the harmony away one tone at a time.
    // ======================================================================

    { {PD_DAMP, 0, 0}, 4 },

    { {nA(4), 0, 0}, 10 },
    { {nFs(4),0, 0}, 10 },
    { {nE(4), 0, 0}, 12 },
    { {nD(4), 0, 0}, 18 },

    { {PD_DAMP, 0, 0}, 6 },


    // One last rolled Dadd2.
    { {nD(3), 0, 0}, 5 },
    { {nA(3), 0, 0}, 5 },
    { {nE(4), 0, 0}, 18 },

    // Resolve the suspended E down to F# / D major color.
    { {nFs(4), 0, 0}, 12 },

    { {PD_DAMP, 0, 0}, 3 },

    // Final open D major chord.
    { {nD(3), nA(3), nFs(4)}, 36 },

    { {PD_DAMP, 0, 0}, 12 },

    { {0, 0, 0}, 0 },
};

// 'gmlast' - converted from gmlast.mid (channel 0) by mid2pdemo.py
// PD_V marks melody notes held >= 0.5s in the MIDI
static const struct pdemo_ev pdemo_gmlast[] = {
    { {nA(2), PD_V|nE(4), 0}, 1 },
    { {nA(3), PD_V|nB(4), 0}, 1 },
    { {PD_V|nCs(5), 0, 0}, 20 },
    { {nCs(3), nGs(3), PD_V|nE(4)}, 1 },
    { {nCs(4), PD_V|nGs(4), 0}, 1 },
    { {PD_V|nE(5), 0, 0}, 17 },
    { {nA(4), 0, 0}, 4 },
    { {PD_V|nD(3), 0, 0}, 1 },
    { {nA(3), PD_V|nFs(4), 0}, 1 },
    { {nD(4), PD_V|nA(4), 0}, 1 },
    { {PD_V|nFs(5), 0, 0}, 20 },
    { {PD_DAMP, 0, 0}, 16 },
    { {nE(3), PD_V|nB(3), 0}, 1 },
    { {nE(4), PD_V|nB(4), 0}, 1 },
    { {PD_V|nGs(5), 0, 0}, 10 },
    { {PD_V|nA(4), 0, 0}, 1 },
    { {nFs(3), nFs(4), PD_V|nCs(5)}, 1 },
    { {PD_V|nA(5), 0, 0}, 4 },
    { {PD_V|nCs(4), 0, 0}, 5 },
    { {nA(4), 0, 0}, 6 },
    { {nGs(5), 0, 0}, 4 },
    { {nFs(5), 0, 0}, 5 },
    { {nCs(3), nGs(4), PD_V|nE(5)}, 19 },
    { {nD(5), 0, 0}, 3 },
    { {nCs(5), 0, 0}, 3 },
    { {nD(3), nFs(4), nCs(5)}, 4 },
    { {nD(5), 0, 0}, 3 },
    { {nE(5), 0, 0}, 4 },
    { {nE(3), nE(4), PD_V|nB(4)}, 30 },
    { {PD_DAMP, 0, 0}, 26 },
    { {PD_V|nE(4), 0, 0}, 13 },
    { {PD_V|nA(3), 0, 0}, 1 },
    { {nB(3), nCs(4), PD_V|nE(4)}, 1 },
    { {PD_V|nCs(5), 0, 0}, 22 },
    { {PD_V|nGs(3), 0, 0}, 1 },
    { {nCs(4), PD_V|nE(4), 0}, 1 },
    { {PD_V|nGs(4), 0, 0}, 1 },
    { {PD_V|nE(5), 0, 0}, 20 },
    { {nA(4), 0, 0}, 4 },
    { {nFs(3), PD_V|nA(3), 0}, 1 },
    { {nD(4), PD_V|nA(4), 0}, 1 },
    { {PD_V|nFs(5), 0, 0}, 26 },
    { {PD_DAMP, 0, 0}, 20 },
    { {nE(3), nB(4), PD_V|nGs(5)}, 12 },
    { {nFs(3), PD_V|nA(4), 0}, 1 },
    { {nCs(4), nFs(4), PD_V|nCs(5)}, 1 },
    { {PD_V|nA(5), 0, 0}, 22 },
    { {nB(5), 0, 0}, 2 },
    { {nCs(6), 0, 0}, 3 },
    { {nGs(3), nE(5), PD_V|nB(5)}, 22 },
    { {nCs(6), 0, 0}, 3 },
    { {nD(6), 0, 0}, 4 },
    { {nA(3), nD(6), 0}, 5 },
    { {PD_V|nE(4), 0, 0}, 2 },
    { {nCs(6), 0, 0}, 2 },
    { {PD_V|nA(5), 0, 0}, 2 },
    { {nA(4), nE(5), 0}, 3 },
    { {PD_V|nD(5), 0, 0}, 4 },
    { {nCs(5), 0, 0}, 2 },
    { {nA(4), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 4 },
    { {nD(3), nD(4), PD_V|nFs(4)}, 30 },
    { {PD_DAMP, 0, 0}, 15 },
    { {PD_V|nA(4), 0, 0}, 1 },
    { {nFs(2), nCs(5), 0}, 1 },
    { {PD_V|nA(5), 0, 0}, 3 },
    { {nCs(3), 0, 0}, 3 },
    { {nFs(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 4 },
    { {nCs(4), 0, 0}, 2 },
    { {nB(5), 0, 0}, 3 },
    { {nCs(6), 0, 0}, 2 },
    { {nGs(2), 0, 0}, 1 },
    { {nE(5), PD_V|nB(5), 0}, 2 },
    { {nE(3), 0, 0}, 2 },
    { {nGs(3), 0, 0}, 3 },
    { {nB(3), 0, 0}, 4 },
    { {nE(4), 0, 0}, 3 },
    { {nCs(6), 0, 0}, 3 },
    { {nD(6), 0, 0}, 4 },
    { {nA(2), nD(6), 0}, 4 },
    { {PD_V|nE(3), 0, 0}, 1 },
    { {nCs(6), 0, 0}, 2 },
    { {PD_V|nA(5), 0, 0}, 2 },
    { {nA(3), nE(5), 0}, 2 },
    { {PD_V|nD(5), 0, 0}, 3 },
    { {nCs(5), 0, 0}, 2 },
    { {nA(4), 0, 0}, 2 },
    { {PD_V|nE(4), 0, 0}, 4 },
    { {nD(3), nD(4), PD_V|nFs(4)}, 1 },
    { {PD_V|nFs(3), 0, 0}, 32 },
    { {PD_DAMP, 0, 0}, 20 },
    { {nE(2), nB(3), PD_V|nGs(4)}, 17 },
    { {nA(2), nCs(4), PD_V|nA(4)}, 2 },
    { {PD_V|nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 4 },
    { {PD_V|nA(4), 0, 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {nGs(3), PD_V|nE(4), 0}, 3 },
    { {nFs(3), PD_V|nD(4), 0}, 6 },
    { {nA(3), 0, 0}, 3 },
    { {nFs(3), 0, 0}, 3 },
    { {nD(4), 0, 0}, 2 },
    { {nGs(3), nE(4), PD_V|nA(4)}, 1 },
    { {nB(3), 0, 0}, 3 },
    { {nA(2), PD_V|nCs(4), 0}, 3 },
    { {PD_V|nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {nGs(3), 0, 0}, 1 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nFs(3), PD_V|nD(4), 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nGs(3), PD_V|nE(4), 0}, 3 },
    { {nB(3), 0, 0}, 2 },
    { {nA(2), PD_V|nCs(4), 0}, 3 },
    { {PD_V|nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nGs(3), PD_V|nE(4), 0}, 3 },
    { {nFs(3), PD_V|nD(4), 0}, 5 },
    { {nA(3), 0, 0}, 3 },
    { {nFs(3), 0, 0}, 3 },
    { {nD(4), 0, 0}, 1 },
    { {nE(4), PD_V|nA(4), 0}, 1 },
    { {nGs(3), nD(4), 0}, 1 },
    { {nB(3), 0, 0}, 2 },
    { {PD_V|nCs(4), 0, 0}, 1 },
    { {PD_V|nA(2), 0, 0}, 15 },
    { {nA(2), 0, 0}, 2 },
    { {nE(3), 0, 0}, 2 },
    { {nFs(3), nGs(3), 0}, 2 },
    { {nA(3), 0, 0}, 1 },
    { {nB(3), 0, 0}, 1 },
    { {nCs(4), 0, 0}, 2 },
    { {nD(4), 0, 0}, 1 },
    { {nE(4), 0, 0}, 1 },
    { {nFs(4), 0, 0}, 1 },
    { {nGs(4), 0, 0}, 2 },
    { {nA(4), 0, 0}, 1 },
    { {nB(4), 0, 0}, 1 },
    { {PD_V|nCs(5), 0, 0}, 1 },
    { {nA(2), 0, 0}, 2 },
    { {nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {nB(3), 0, 0}, 3 },
    { {nCs(4), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 2 },
    { {nCs(3), PD_V|nE(5), 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nCs(4), 0, 0}, 3 },
    { {nE(4), 0, 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nD(3), nFs(5), 0}, 3 },
    { {PD_V|nA(3), 0, 0}, 2 },
    { {nD(4), 0, 0}, 3 },
    { {nE(4), 0, 0}, 3 },
    { {PD_V|nFs(4), 0, 0}, 3 },
    { {nD(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 9 },
    { {nE(3), nB(4), PD_V|nGs(5)}, 2 },
    { {nB(3), 0, 0}, 3 },
    { {nE(4), 0, 0}, 3 },
    { {nFs(3), nCs(5), PD_V|nA(5)}, 3 },
    { {nCs(4), 0, 0}, 3 },
    { {nFs(4), 0, 0}, 3 },
    { {nA(4), 0, 0}, 2 },
    { {nGs(5), 0, 0}, 3 },
    { {nFs(5), 0, 0}, 2 },
    { {PD_V|nCs(3), 0, 0}, 1 },
    { {PD_V|nE(5), 0, 0}, 2 },
    { {PD_V|nGs(3), 0, 0}, 3 },
    { {PD_V|nCs(4), 0, 0}, 3 },
    { {nE(4), 0, 0}, 2 },
    { {nD(5), 0, 0}, 3 },
    { {nCs(5), 0, 0}, 3 },
    { {nD(3), nE(4), nCs(5)}, 5 },
    { {nD(5), 0, 0}, 2 },
    { {nE(5), 0, 0}, 1 },
    { {nE(3), nE(4), nB(4)}, 12 },
    { {PD_V|nA(4), 0, 0}, 1 },
    { {nGs(4), 0, 0}, 1 },
    { {nB(3), nE(4), 0}, 2 },
    { {nGs(3), 0, 0}, 6 },
    { {nE(3), PD_V|nE(4), 0}, 3 },
    { {nA(2), PD_V|nCs(5), 0}, 3 },
    { {nE(3), 0, 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {nB(3), 0, 0}, 6 },
    { {nCs(4), PD_V|nE(4), 0}, 3 },
    { {nCs(3), PD_V|nE(5), 0}, 2 },
    { {PD_V|nA(3), 0, 0}, 3 },
    { {PD_V|nCs(4), 0, 0}, 3 },
    { {nA(4), 0, 0}, 6 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nD(3), PD_V|nFs(5), 0}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {nD(4), 0, 0}, 3 },
    { {nE(4), 0, 0}, 3 },
    { {nFs(4), 0, 0}, 5 },
    { {nD(4), 0, 0}, 10 },
    { {nE(2), nB(4), PD_V|nGs(5)}, 9 },
    { {nFs(3), nCs(5), PD_V|nA(5)}, 2 },
    { {nCs(4), 0, 0}, 3 },
    { {nFs(4), 0, 0}, 3 },
    { {nA(4), 0, 0}, 3 },
    { {nB(5), 0, 0}, 2 },
    { {nCs(6), 0, 0}, 3 },
    { {nGs(3), nE(5), PD_V|nB(5)}, 2 },
    { {nE(4), 0, 0}, 3 },
    { {nGs(4), 0, 0}, 3 },
    { {nB(4), 0, 0}, 3 },
    { {nCs(6), 0, 0}, 3 },
    { {nD(6), 0, 0}, 2 },
    { {nA(3), nD(6), 0}, 3 },
    { {nE(4), 0, 0}, 1 },
    { {nCs(6), 0, 0}, 1 },
    { {PD_V|nA(5), 0, 0}, 1 },
    { {nA(4), nE(5), 0}, 3 },
    { {nE(4), PD_V|nD(5), 0}, 3 },
    { {nCs(4), 0, 0}, 1 },
    { {nA(4), nCs(5), 0}, 2 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nD(3), nFs(4), 0}, 2 },
    { {PD_V|nA(3), 0, 0}, 3 },
    { {nD(4), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {PD_V|nA(3), 0, 0}, 3 },
    { {nFs(3), 0, 0}, 17 },
    { {nFs(2), nCs(5), PD_V|nA(5)}, 3 },
    { {nCs(3), 0, 0}, 2 },
    { {nFs(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nB(5), 0, 0}, 3 },
    { {nCs(6), 0, 0}, 2 },
    { {nGs(2), PD_V|nB(5), 0}, 1 },
    { {PD_V|nE(5), 0, 0}, 2 },
    { {nE(3), 0, 0}, 3 },
    { {nGs(3), 0, 0}, 3 },
    { {nB(3), 0, 0}, 3 },
    { {nCs(6), 0, 0}, 2 },
    { {nD(6), 0, 0}, 3 },
    { {nA(2), nD(6), 0}, 3 },
    { {nE(3), nCs(6), 0}, 1 },
    { {PD_V|nA(5), 0, 0}, 1 },
    { {nA(3), nE(5), 0}, 3 },
    { {nB(3), PD_V|nD(5), 0}, 4 },
    { {nCs(5), 0, 0}, 1 },
    { {nCs(4), nA(4), 0}, 1 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nD(3), nFs(4), 0}, 3 },
    { {PD_V|nFs(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nD(4), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 2 },
    { {PD_V|nA(3), 0, 0}, 3 },
    { {PD_V|nFs(3), 0, 0}, 24 },
    { {nE(2), nB(3), nGs(4)}, 3 },
    { {nE(4), 0, 0}, 3 },
    { {nB(2), nD(4), 0}, 3 },
    { {nA(2), nCs(4), PD_V|nA(4)}, 3 },
    { {PD_V|nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nA(4), 0, 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {nA(2), nE(4), nA(4)}, 3 },
    { {nFs(3), nD(4), PD_V|nA(4)}, 5 },
    { {nD(4), nE(4), 0}, 1 },
    { {nA(3), 0, 0}, 1 },
    { {nFs(3), 0, 0}, 2 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nGs(3), nD(4), 0}, 2 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nCs(4), nA(4), 0}, 1 },
    { {PD_V|nA(2), 0, 0}, 2 },
    { {PD_V|nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {nGs(3), nE(4), 0}, 3 },
    { {nFs(3), nD(4), nA(4)}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nGs(3), nE(4), nA(4)}, 2 },
    { {nB(3), 0, 0}, 3 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nE(3), nB(3), 0}, 3 },
    { {nA(2), PD_V|nCs(4), 0}, 3 },
    { {PD_V|nE(3), 0, 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nGs(3), PD_V|nE(4), 0}, 3 },
    { {nFs(3), PD_V|nD(4), 0}, 5 },
    { {nA(3), 0, 0}, 3 },
    { {nFs(3), 0, 0}, 3 },
    { {nD(4), PD_V|nA(4), 0}, 1 },
    { {nD(4), PD_V|nE(4), 0}, 1 },
    { {nGs(3), nB(3), 0}, 3 },
    { {nA(2), nE(3), PD_V|nCs(4)}, 20 },
    { {PD_DAMP, 0, 0}, 10 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nE(5), 0, 0}, 3 },
    { {nFs(2), PD_V|nB(4), 0}, 3 },
    { {nCs(3), 0, 0}, 3 },
    { {nFs(3), 0, 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nE(5), 0, 0}, 3 },
    { {nGs(2), PD_V|nB(4), 0}, 3 },
    { {nE(3), 0, 0}, 3 },
    { {nGs(3), 0, 0}, 2 },
    { {nB(3), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nE(5), 0, 0}, 3 },
    { {nA(2), PD_V|nB(4), 0}, 3 },
    { {nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {PD_V|nB(3), 0, 0}, 6 },
    { {nCs(4), PD_V|nE(4), 0}, 16 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nE(5), 0, 0}, 2 },
    { {nFs(2), 0, 0}, 1 },
    { {PD_V|nB(4), 0, 0}, 2 },
    { {nCs(3), 0, 0}, 3 },
    { {nFs(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nE(5), 0, 0}, 2 },
    { {PD_V|nGs(2), 0, 0}, 1 },
    { {PD_V|nB(4), 0, 0}, 2 },
    { {nE(3), 0, 0}, 3 },
    { {nGs(3), 0, 0}, 3 },
    { {nB(3), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nE(5), 0, 0}, 3 },
    { {nA(2), PD_V|nB(4), 0}, 2 },
    { {nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nB(3), 0, 0}, 6 },
    { {nCs(4), PD_V|nE(4), 0}, 15 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nE(5), 0, 0}, 3 },
    { {nFs(2), PD_V|nB(4), 0}, 3 },
    { {nCs(3), 0, 0}, 2 },
    { {nFs(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nE(5), 0, 0}, 3 },
    { {nGs(2), PD_V|nB(4), 0}, 3 },
    { {nE(3), 0, 0}, 2 },
    { {nGs(3), 0, 0}, 3 },
    { {nB(3), 0, 0}, 3 },
    { {nE(4), 0, 0}, 3 },
    { {nE(5), 0, 0}, 2 },
    { {nE(4), nB(4), 0}, 1 },
    { {nA(2), nCs(5), 0}, 3 },
    { {PD_V|nE(3), 0, 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {nCs(3), nB(3), PD_V|nGs(4)}, 6 },
    { {nGs(3), nE(4), 0}, 3 },
    { {nD(3), PD_V|nFs(3), 0}, 25 },
    { {PD_DAMP, 0, 0}, 16 },
    { {nB(1), nD(4), PD_V|nFs(4)}, 3 },
    { {PD_V|nFs(2), 0, 0}, 3 },
    { {PD_V|nB(2), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nGs(4), 0, 0}, 2 },
    { {nA(4), 0, 0}, 3 },
    { {nCs(2), nB(3), PD_V|nE(4)}, 3 },
    { {PD_V|nA(2), 0, 0}, 3 },
    { {nCs(3), 0, 0}, 3 },
    { {nE(3), 0, 0}, 3 },
    { {nGs(4), 0, 0}, 3 },
    { {nA(4), 0, 0}, 3 },
    { {nD(2), nFs(4), nA(4)}, 9 },
    { {nA(2), nFs(4), nCs(5)}, 8 },
    { {nE(2), nFs(4), PD_V|nB(4)}, 2 },
    { {PD_V|nGs(4), 0, 0}, 30 },
    { {PD_DAMP, 0, 0}, 20 },
    { {nE(3), 0, 0}, 2 },
    { {nFs(3), 0, 0}, 2 },
    { {nGs(3), 0, 0}, 2 },
    { {nA(3), 0, 0}, 1 },
    { {nB(3), 0, 0}, 1 },
    { {nCs(4), 0, 0}, 2 },
    { {nD(4), 0, 0}, 1 },
    { {nE(4), 0, 0}, 1 },
    { {nFs(4), 0, 0}, 1 },
    { {nGs(4), 0, 0}, 1 },
    { {nA(4), 0, 0}, 2 },
    { {nB(4), 0, 0}, 1 },
    { {PD_V|nCs(5), 0, 0}, 1 },
    { {nA(2), 0, 0}, 2 },
    { {nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {nB(3), 0, 0}, 3 },
    { {nCs(4), 0, 0}, 2 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nCs(3), PD_V|nE(5), 0}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {nCs(4), 0, 0}, 3 },
    { {nE(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nD(3), nFs(5), 0}, 2 },
    { {PD_V|nA(3), 0, 0}, 3 },
    { {PD_V|nD(4), 0, 0}, 3 },
    { {nE(4), 0, 0}, 3 },
    { {nFs(4), 0, 0}, 3 },
    { {nE(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 9 },
    { {nE(3), nB(4), nGs(5)}, 3 },
    { {nB(3), nE(5), 0}, 2 },
    { {nE(4), 0, 0}, 1 },
    { {nB(4), 0, 0}, 2 },
    { {nFs(3), 0, 0}, 1 },
    { {nCs(5), PD_V|nA(5), 0}, 2 },
    { {nCs(4), 0, 0}, 3 },
    { {nFs(4), 0, 0}, 3 },
    { {nA(4), 0, 0}, 3 },
    { {nB(4), nGs(5), 0}, 2 },
    { {nFs(5), 0, 0}, 3 },
    { {nCs(3), nB(4), PD_V|nE(5)}, 3 },
    { {PD_V|nGs(3), 0, 0}, 3 },
    { {PD_V|nCs(4), 0, 0}, 3 },
    { {nE(4), 0, 0}, 2 },
    { {nD(5), 0, 0}, 3 },
    { {nCs(5), 0, 0}, 3 },
    { {nD(3), nE(4), nCs(5)}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {nD(5), 0, 0}, 1 },
    { {nE(5), 0, 0}, 2 },
    { {nE(3), nE(4), PD_V|nB(4)}, 9 },
    { {nA(3), 0, 0}, 4 },
    { {nGs(4), PD_V|nA(4), 0}, 1 },
    { {nE(4), 0, 0}, 1 },
    { {nB(3), 0, 0}, 3 },
    { {nGs(3), 0, 0}, 6 },
    { {nE(3), PD_V|nE(4), 0}, 3 },
    { {nA(2), PD_V|nCs(5), 0}, 2 },
    { {nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nB(3), 0, 0}, 3 },
    { {nCs(4), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nCs(3), PD_V|nE(5), 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nCs(4), 0, 0}, 9 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nD(3), nFs(5), 0}, 3 },
    { {PD_V|nA(3), 0, 0}, 3 },
    { {nD(4), 0, 0}, 2 },
    { {nE(4), 0, 0}, 3 },
    { {PD_V|nFs(4), 0, 0}, 3 },
    { {nD(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 9 },
    { {nE(3), nB(4), PD_V|nGs(5)}, 3 },
    { {nB(3), 0, 0}, 3 },
    { {nE(4), 0, 0}, 3 },
    { {nFs(3), nCs(5), PD_V|nA(5)}, 3 },
    { {nCs(4), 0, 0}, 2 },
    { {nFs(4), 0, 0}, 3 },
    { {nA(4), 0, 0}, 3 },
    { {nB(5), 0, 0}, 3 },
    { {nCs(6), 0, 0}, 2 },
    { {nGs(3), PD_V|nB(5), 0}, 1 },
    { {PD_V|nE(5), 0, 0}, 2 },
    { {nE(4), 0, 0}, 3 },
    { {nGs(4), 0, 0}, 3 },
    { {nB(4), 0, 0}, 3 },
    { {nCs(6), 0, 0}, 2 },
    { {nD(6), 0, 0}, 3 },
    { {nA(3), nD(6), 0}, 3 },
    { {nE(4), 0, 0}, 1 },
    { {PD_V|nA(5), nCs(6), 0}, 1 },
    { {nE(5), 0, 0}, 1 },
    { {nA(4), 0, 0}, 2 },
    { {PD_V|nD(5), 0, 0}, 2 },
    { {nE(4), 0, 0}, 2 },
    { {nCs(5), 0, 0}, 1 },
    { {nA(4), 0, 0}, 1 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nD(3), nFs(4), 0}, 3 },
    { {PD_V|nA(3), 0, 0}, 3 },
    { {nD(4), 0, 0}, 3 },
    { {nE(4), 0, 0}, 2 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {PD_V|nD(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 19 },
    { {nFs(2), nCs(5), PD_V|nA(5)}, 2 },
    { {nCs(3), 0, 0}, 3 },
    { {nFs(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nB(5), 0, 0}, 2 },
    { {nCs(6), 0, 0}, 3 },
    { {nGs(2), nE(5), PD_V|nB(5)}, 3 },
    { {nE(3), 0, 0}, 3 },
    { {nGs(3), 0, 0}, 2 },
    { {nB(3), 0, 0}, 3 },
    { {nCs(6), 0, 0}, 3 },
    { {nD(6), 0, 0}, 2 },
    { {nA(2), 0, 0}, 1 },
    { {nD(6), 0, 0}, 2 },
    { {nE(3), 0, 0}, 1 },
    { {nCs(6), 0, 0}, 1 },
    { {PD_V|nA(5), 0, 0}, 1 },
    { {nA(3), nE(5), 0}, 3 },
    { {nB(3), PD_V|nD(5), 0}, 2 },
    { {nCs(4), 0, 0}, 2 },
    { {nCs(5), 0, 0}, 1 },
    { {nA(4), 0, 0}, 1 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nD(3), nD(4), nFs(4)}, 3 },
    { {PD_V|nFs(3), 0, 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {nD(4), 0, 0}, 3 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {PD_V|nA(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {PD_V|nD(4), 0, 0}, 4 },
    { {nA(3), 0, 0}, 1 },
    { {PD_V|nE(4), 0, 0}, 3 },
    { {PD_V|nA(3), 0, 0}, 3 },
    { {PD_V|nD(4), 0, 0}, 20 },
    { {PD_DAMP, 0, 0}, 6 },
    { {nE(2), nE(4), nGs(4)}, 3 },
    { {nB(2), 0, 0}, 2 },
    { {nE(3), 0, 0}, 1 },
    { {nB(3), 0, 0}, 3 },
    { {nA(2), nCs(4), nA(4)}, 3 },
    { {PD_V|nE(3), 0, 0}, 2 },
    { {nA(3), 0, 0}, 3 },
    { {nA(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nGs(3), nE(4), 0}, 3 },
    { {nFs(3), nD(4), PD_V|nA(4)}, 9 },
    { {nFs(3), 0, 0}, 3 },
    { {nD(4), PD_V|nA(4), 0}, 1 },
    { {PD_V|nE(4), 0, 0}, 1 },
    { {nD(4), 0, 0}, 1 },
    { {nB(3), 0, 0}, 2 },
    { {nA(2), PD_V|nCs(4), 0}, 3 },
    { {PD_V|nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nE(4), 0, 0}, 6 },
    { {nGs(3), nE(4), nA(4)}, 3 },
    { {nFs(3), nD(4), nA(4)}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {PD_V|nGs(3), 0, 0}, 1 },
    { {nE(4), nA(4), 0}, 2 },
    { {nB(3), 0, 0}, 3 },
    { {nE(4), PD_V|nA(4), 0}, 3 },
    { {nE(3), nB(3), 0}, 3 },
    { {nA(2), PD_V|nCs(4), 0}, 3 },
    { {PD_V|nE(3), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nA(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 2 },
    { {nGs(3), nE(4), nA(4)}, 4 },
    { {nFs(3), nD(4), nA(4)}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nA(4), 0, 0}, 3 },
    { {nA(3), 0, 0}, 3 },
    { {nGs(3), nE(4), nA(4)}, 4 },
    { {nB(3), 0, 0}, 4 },
    { {nA(2), nE(4), PD_V|nA(4)}, 2 },
    { {PD_V|nCs(4), 0, 0}, 24 },
    { {PD_DAMP, 0, 0}, 12 },
    { {0, 0, 0}, 0 },
};


#define PDEMO_STEP_US   80000u
#define PDEMO_PRESET    3               // organ

static const struct {
    const struct pdemo_ev *song;
    const char *name;
} pdemo_songs[] = {
    { pdemo_lanterns, "lanterns" },
    { pdemo_gmlast,   "gmlast" },
};
#define NUM_PDEMOS ((int)(sizeof(pdemo_songs) / sizeof(pdemo_songs[0])))

static const struct pdemo_ev *pdemo_song;   // start of the playing song
static const struct pdemo_ev *pdemo_ev;
static uint32_t pdemo_next;

static void pdemo_fire(void)
{
    if (pdemo_ev->n[0] == PD_DAMP) {
        for (int nv = 0; nv < poly_nvoices; ++nv) {
            if (poly_v[nv].level)
                poly_v[nv].ramp = -1;   // organist lifts hands: soft release
            poly_v[nv].vocal = 0;       // melody protection ends too
        }
        return;
    }
    for (int i = 0; i < 3; ++i) {
        uint8_t n = pdemo_ev->n[i];
        if (n)
            poly_note_on_ex((n & 0x7F) % 12, (n & 0x7F) / 12,
                            (n & PD_V) != 0,
                            (n & PD_V) ? 127 : 100, poly_preset);
    }
}

// Fade the PCM chroma's carrier duty between 'pin low' and mid-scale
// silence over ~10ms, so starting and stopping the synth doesn't step the
// speaker by half the supply (the same pop the note ramps fix, one layer
// down)
static void pcm_carrier_fade(int up)
{
    for (int d = up ? 1 : 127; up ? d <= 127 : d >= 1; d += up ? 2 : -2) {
        prism_set_count2_compare((uint8_t)d);
        uint32_t t0 = read_time();
        while (read_time() - t0 < us_ticks(150))
            ;
    }
}

static uint32_t pe_refill, pe_underruns, pe_max_us, pe_blocks, pe_bb;

// Bring the whole poly output chain up: PCM chroma, carrier, sample
// clock, primed ping-pong buffers, ISR streaming.  Shared by the
// keyboard/demo command and the MIDI player.
int poly_engine_start(void)
{
    printf("\nLoading PCM Chroma for the poly synth\n");

    prism_comm_write(254);                      // carrier period
    prism_set_count2_compare(1);                // start at the pin's idle
    prism_set_count1_preload(poly_preload());
    poly_step_scale = (uint32_t)((((uint64_t)(poly_interp ? POLY_OUT_HZ
                                               : POLY_RATE)
                                   * poly_out_period()) << 16) / clock_hz);
    if (poly_interp)
        printf("2x interpolated output\n");

    int res = prism_load_chroma(chroma_pcm, CHROMA_PCM_CTRL);

    chroma_set_loaded(chroma_pcm);
    if (res) {
        printf("load FAILED, error mask 0x%05x\n", res);
        return -1;
    }
    chroma_set_loaded(chroma_pcm);
    prism_disable_interrupt();
    prism_clear_interrupt();
    set_gpio_func(7, 8);

    pcm_carrier_fade(1);                        // ease up to mid scale

    poly_nvoices = clock_hz >= 85000000u ? 4 : 3;
    poly_drum_voice = -1;
    memset(poly_v, 0, sizeof(poly_v));
    memset(poly_buf, 128, sizeof(poly_buf));

    // Prime both buffers, then let the ISR stream them (mode 2)
    poly_render(poly_buf[0]);
    poly_render(poly_buf[1]);
    pe_bb = (poly_interp ? 2u : 1u) * POLY_BLOCK;         // block bytes

    l4z_ch.rd = (uint32_t *)(void *)poly_buf[0];
    l4z_ch.end = (uint32_t *)(void *)(poly_buf[0] + pe_bb);
    l4z_ch.next = (uint32_t *)(void *)poly_buf[1];
    l4z_ch.next_end = (uint32_t *)(void *)(poly_buf[1] + pe_bb);
    l4z_ch.consumed = 0;
    l4z_ch.active = 2;
    prism_enable_interrupt();

    pe_refill = pe_underruns = pe_max_us = pe_blocks = 0;
    return 0;
}

// One pass of refill housekeeping; returns nonzero when a buffer was
// rendered (the caller's idle loop needs no other pacing)
int poly_engine_service(void)
{
    if (!l4z_ch.consumed)
        return 0;
    l4z_ch.consumed = 0;
    uint32_t t0 = read_time();
    poly_render(poly_buf[pe_refill]);
    l4z_ch.next = (uint32_t *)(void *)poly_buf[pe_refill];
    l4z_ch.next_end = (uint32_t *)(void *)(poly_buf[pe_refill] + pe_bb);
    pe_refill ^= 1;
    uint32_t dt = read_time() - t0;
    if (dt > pe_max_us)
        pe_max_us = dt;
    if (l4z_ch.consumed)
        ++pe_underruns;
    ++pe_blocks;
    return 1;
}

void poly_engine_stop(void)
{
    l4z_ch.active = 0;
    prism_disable_interrupt();
    prism_clear_interrupt();
    pcm_carrier_fade(0);                // ease back down before the cut
    prism_disable();

    printf("\n%lu blocks, %lu underruns, max render %luus"
           " (budget %luus per buffer)\n",
           (unsigned long)pe_blocks, (unsigned long)pe_underruns,
           (unsigned long)(((uint64_t)pe_max_us * 64000000u) / clock_hz),
           (unsigned long)(((uint64_t)pe_bb * poly_out_period()
                            * 1000000u) / clock_hz));
}

void cmd_synthp(int argc, char *argv[])
{
    // '-i' anywhere: 2x interpolated output (A/B against the plain
    // 12.5kHz stream)
    poly_interp = 0;
    for (int a = 1; a < argc; a++)
        if (!strcmp(argv[a], "-i")) {
            poly_interp = 1;
            for (int b = a; b < argc - 1; b++)
                argv[b] = argv[b + 1];
            argc--;
            a--;
        }

    // The interpolated stream only fits the refill budget with the
    // 85MHz block time: at 64MHz the doubled ISR rate + 2048-byte
    // PSRAM emit measured 81.8ms against the 81.9ms budget (demo 2
    // underruns = the popping) - refuse rather than crackle.
    if (poly_interp && clock_hz < 85000000u) {
        printf("-i needs the 85MHz clock (run --freq 85) - playing plain\n");
        poly_interp = 0;
    }

    int demo = argc > 1 && !strcmp(argv[1], "demo");
    uint32_t which = 1;

    if (demo && argc > 2 && (!parse_u32(argv[2], &which) ||
                             which < 1 || which > (uint32_t)NUM_PDEMOS)) {
        printf("poly demos:");
        for (int i = 0; i < NUM_PDEMOS; ++i)
            printf(" %d = %s%s", i + 1, pdemo_songs[i].name,
                   i < NUM_PDEMOS - 1 ? "," : "\n");
        return;
    }

    if (poly_engine_start() != 0)
        return;
    poly_preset = 0;
    syn.octave = 3;

    if (demo) {
        poly_preset = PDEMO_PRESET;
        pdemo_song = pdemo_songs[which - 1].song;
        pdemo_ev = pdemo_song;
        printf("~~~ poly synth demo: %s ~~~  (any key stops)\n\n[%s] ",
               pdemo_songs[which - 1].name,
               poly_presets[poly_preset].name);
    } else {
        printf(
"~~~ PRISM poly synth (3 voices) ~~~\n"
"  same keyboard as 'synth'; chords ring while you play more notes\n"
"  o / p  instrument   - / =  octave   space  silence all   ESC quits\n"
"  instruments: ");
        for (int i = 0; i < NUM_POLY_PRESETS; ++i)
            printf("%s ", poly_presets[i].name);
        printf("\n\n[%s] ", poly_presets[poly_preset].name);
    }



    if (demo) {
        pdemo_next = read_time();       // first event fires immediately
    }

    int demo_done = 0;                  // last demo event fired; ring out

    for (;;) {
        int c = uart_getc();

        if (demo) {
            if (c != -1)                // any key stops the demo
                break;
            if (!demo_done &&
                (int32_t)(read_time() - pdemo_next) >= 0) {
                pdemo_fire();
                pdemo_next += us_ticks((uint32_t)pdemo_ev->len * PDEMO_STEP_US);
                ++pdemo_ev;
                if (pdemo_ev->len == 0)
                    demo_done = 1;      // no loop - let the last notes ring
            }
            if (demo_done && !poly_active())
                break;                  // song finished: back to the prompt
        } else {
            if (c == 0x1b || c == '`')
                break;
            if (c != -1)
                poly_key(c);
        }

        poly_engine_service();
    }

    poly_engine_stop();
    printf("synthp off\n");
}
