#!/bin/sh
# Embed chroma sources for the TUI's source tabs (the target has no
# filesystem): the yosys-prism .lst STEW decode AND the hand-written
# chroma .v files.
#
#   tools/lst2c.sh <lst-dir> <v-dir> <name>... > chroma_lsts.c
#
# Emits chroma_lst_<name>[] / chroma_v_<name>[] plus name/text registry
# tables, in the argument order (keep it matching the chroma table in
# console.c).

lstdir="$1"
vdir="$2"
shift 2

emit_text() {
  sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/"/' -e 's/$/\\n"/' "$1"
}

echo "/* Generated by tools/lst2c.sh - do not edit."
echo " * .lst from $lstdir, .v from $vdir */"
echo
for n in "$@"; do
  echo "const char chroma_lst_$n[] ="
  emit_text "$lstdir/chroma_$n.lst"
  echo ";"
  echo
  echo "const char chroma_v_$n[] ="
  emit_text "$vdir/chroma_$n.v"
  echo ";"
  echo
done
echo "const char * const chroma_lst_names[] = {"
for n in "$@"; do
  echo "  \"$n\","
done
echo "  0"
echo "};"
echo
echo "const char * const chroma_lst_texts[] = {"
for n in "$@"; do
  echo "  chroma_lst_$n,"
done
echo "  0"
echo "};"
echo
echo "const char * const chroma_v_texts[] = {"
for n in "$@"; do
  echo "  chroma_v_$n,"
done
echo "  0"
echo "};"
