// WS2812 "NeoPixel" LED demo ('flashy' command).
//
// Loads the WS2812 chroma (data on uo_out[1]), sets its bit timing, then
// hands over to the pattern generator in leddemo.c.

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <gpio.h>
#include <csr.h>
#include <uart.h>
#include <prism.h>
#include "prism_tui.h"

// Chroma bitstream generated by the PRISM Yosys backend (chroma_ws2812.sv,
// tinyqv16.cfg).  Pairs of {STEW MSW, STEW LSW} in load order.
const uint32_t chroma_ws2812[PRISM_CHROMA_WORDS*2] = {
    0x00000bc0, 0x00001000,
    0x00000940, 0x0000301d,
    0x00000aa2, 0x0200d01e,
    0x00000aa2, 0x0200d016,
    0x00000aa0, 0x0a01b016,
    0x00000960, 0x0a01900f,
    0x00000a90, 0x0a01501e,
    0x000009b8, 0x20003190,
};
#define CHROMA_WS2812_CTRL  0x00002500u
// Pattern generator in leddemo.c
void flashy(int argc, char *argv[]);

void cmd_flashy(int argc, char *argv[])
{
    printf("\nLoading WS2812 Chroma\n");
    int res = prism_load_chroma(chroma_ws2812, CHROMA_WS2812_CTRL);
    chroma_set_loaded(chroma_ws2812);
    check(res == 0, "load WS2812 chroma");

    // Load it again, this time validating the first load word by word as
    // it is shifted out of the STEW array
    res = prism_load_chroma_verify(chroma_ws2812, chroma_ws2812,
                                   CHROMA_WS2812_CTRL);
    check(res == 0, "reload while validating WS2812 load");
    if (res)
        printf("    error mask %05x\n", res);

    // Mux the uo[1] (audio PMOD output) to our peripheral
    set_gpio_func(1, 8);

    // Configure the timebase for ws2812
    prism_set_count2_compare(51);
    prism_comm_write(26);

    // Load the Chroma
    flashy(argc, argv);
}
